apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-go
  labels:
    app: demo-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-go
  template:
    metadata:
      labels:
        app: demo-go
        app.kubernetes.io/name: go
        app.kubernetes.io/instance: demo-go
    spec:
      containers:
        - name: demo-go
          image: kevin2025/demo-go:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts: []
      volumes: []