apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-go
  labels:
    app: demo-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-go
  template:
    metadata:
      labels:
        app: demo-go
        app.kubernetes.io/name: go
        app.kubernetes.io/instance: demo-go
    spec:
      containers:
        - name: demo-go
          image: kevin2025/demo-go:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            httpGet:
              port: http
              path: "/health/startup"
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              port: http
              path: "/health/liveness"
            periodSeconds: 10
            failureThreshold: 2
          readinessProbe:
            httpGet:
              port: http
              path: "/health/readiness"
            periodSeconds: 10
            failureThreshold: 180
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts: []
      volumes: []