name: Check
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.22.4

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1
