name: Docker Publish
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: kevin2025/example-go

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: kevin2025
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: main
          platforms: linux/amd64
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_COMMIT_SHA=${{ env.SHORT_SHA }}
            GIT_TAG=${{ github.ref_type == 'tag' && github.ref_name || '' }}